-- Personal Finance Platform — Snowflake Schema
-- Run this once to set up the required tables

CREATE DATABASE IF NOT EXISTS PERSONAL_FINANCE;
USE DATABASE PERSONAL_FINANCE;
CREATE SCHEMA IF NOT EXISTS APP;
USE SCHEMA APP;

-- Daily Expenses
CREATE TABLE IF NOT EXISTS DAILY_EXPENSES (
  ID VARCHAR(36) PRIMARY KEY,
  USER_ID VARCHAR(50) DEFAULT 'ashish',
  DATE DATE NOT NULL,
  AMOUNT NUMBER(12,2) NOT NULL,
  CATEGORY VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(500),
  PAYMENT_METHOD VARCHAR(20), -- Cash, UPI, Card, Bank Transfer
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Investment Holdings (current state of each holding)
CREATE TABLE IF NOT EXISTS INVESTMENT_HOLDINGS (
  ID VARCHAR(36) PRIMARY KEY,
  USER_ID VARCHAR(50) DEFAULT 'ashish',
  TYPE VARCHAR(30) NOT NULL, -- mutual_fund, stock, fd, rd, ppf, epf, nps, ssy, gold_physical, gold_sgb, gold_digital, real_estate
  NAME VARCHAR(200) NOT NULL,
  PROVIDER VARCHAR(100),    -- AMC, Broker, Bank name
  INVESTED_AMOUNT NUMBER(14,2) DEFAULT 0,
  CURRENT_VALUE NUMBER(14,2) DEFAULT 0,
  UNITS NUMBER(12,4),
  RATE_OR_NAV NUMBER(12,4),
  START_DATE DATE,
  MATURITY_DATE DATE,
  FREQUENCY VARCHAR(20),    -- Monthly, Quarterly, Yearly, One-time
  STATUS VARCHAR(20) DEFAULT 'active',
  METADATA VARIANT,         -- Type-specific fields as JSON
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Investment Transactions (buy/sell/SIP/dividend history)
CREATE TABLE IF NOT EXISTS INVESTMENT_TRANSACTIONS (
  ID VARCHAR(36) PRIMARY KEY,
  HOLDING_ID VARCHAR(36) NOT NULL,
  USER_ID VARCHAR(50) DEFAULT 'ashish',
  TYPE VARCHAR(20) NOT NULL, -- buy, sell, sip, dividend, interest, contribution
  DATE DATE NOT NULL,
  AMOUNT NUMBER(14,2),
  UNITS NUMBER(12,4),
  NAV_OR_PRICE NUMBER(12,4),
  NOTES VARCHAR(500),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Budget Limits per category
CREATE TABLE IF NOT EXISTS BUDGET_LIMITS (
  ID VARCHAR(36) PRIMARY KEY,
  USER_ID VARCHAR(50) DEFAULT 'ashish',
  CATEGORY VARCHAR(50) NOT NULL,
  MONTHLY_LIMIT NUMBER(12,2) NOT NULL,
  ALERT_THRESHOLD NUMBER(3,2) DEFAULT 0.80
);
